### ISSUE TITLE
Research Existing Sidebar Implementations

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#12]
Let's see if we can find any open source implementations of the sidebar for the IDE that lists out the files and lets you do things like add a new file, rename a file, delete a file, and open a file.

**Comment by curran** [comment]
Wow it's a jungle in the VSCode source code!

I found something called `SidebarPart` https://github.com/microsoft/vscode/blob/14d1b6f79ec1ad7a290c4930f5047838500a9f24/src/vs/workbench/browser/parts/paneCompositePart.ts#L15

**Comment by curran** [comment]
Maybe something in here?

https://github.com/microsoft/vscode/tree/main/src/vs/workbench/browser/parts/sidebar

**Comment by curran** [comment]
Also let's look at https://github.com/codesandbox/codesandbox-client

**Comment by curran** [comment]
And maybe StackBlitz

**Comment by curran** [comment]
Hey I think I found the implementation for the CodeSandbox sidebar!

https://github.com/codesandbox/codesandbox-client/blob/389073613e06eee944231f4aeef9dfa746c1b947/packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/index.tsx#L100

**Comment by Anooj-Pai** [comment]
That’s perfect! We just need to adapt it into our system and we’re good to
go!

Also I sent a mock-up on discord
