### ISSUE TITLE
Keyboard Shortcut to Close Tab

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#156]
Normally would go for CTRL+w, but that closes the Chrome tab.

How about Alt+w?

**Comment by 05hiteshbansal** [comment]
@curran  can you explain me more about the purpose and result you expected from key shortcut

**Comment by curran** [comment]
As a user of VSCode and Chrome, I'm used to the ability to close tabs with my keyboard. Both VSCode and Chrome support the shortcut Ctrl+w to close a tab. As a user of VZCode, I want a similar way to quickly close a tab using the keyboard, without the need to use the mouse to click on the little "X" button to close the tab.

An example:


![VZCode Interface](https://user-images.githubusercontent.com/68416/224690259-293c75c5-5970-4066-80e4-b9dee568e10d.png)

The currently open tab in this screenshot is `index.html`. I want to be able to close that tab using the keyboard.

Perhaps Alt+w may be a good candidate, because it's similar to Ctrl+w.

Maybe other tools have a different keyboard shortcut as an alternative to Ctrl+w.
