### ISSUE TITLE
VSCode-ish: Jump to Definition of Variable

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#177]
As a user of VZCode, I want to be able to hold CTRL and click on a variable name to jump to the definition of that variable, just like I can in VSCode.

**Comment by servesh-chaturvedi** [comment]
Hi Curran, really love your work and videos. I wanted to understand if there is any particular reason for preferring codemirror to monaco editor. It closely resembles the VSCode experience and also feature-rich so less things to implement.

**Comment by curran** [comment]
The main reason is that when I looked into Monaco, it just really felt quite bloated and cumbersome. I had been following CodeMirror 6 developments for some time (see this early piece: [CodeMirror 6 Experiments](https://currankelleher.medium.com/codemirror-6-experiments-a3930bf03781)), and am deeply aligned with Marjin's development approach and goals, especially around the plugin architecture and the mobile usability. I've [read](https://gitlab.com/gitlab-org/gitlab/-/issues/387586) that Monaco does not work on mobile, which for me is a deal breaker as one of my ultimate goals is to make a code editor that is actually somewhat usable on mobile, for folks who want to learn to code but don't have access to a laptop (like folks in India - there are many people like this).

I also have a history of working with CodeMirror 5 + ShareDB for the real-time integration, and was able to "unlock" that CodeMirror 6 + ShareDB integration successfully, which took a ton of work. So even if Monaco is great, there's the sunk cost of that integration that's already behind me. Doing a similar integration with Monaco + ShareDB seems like a scary huge task that may turn out to be impossible.

This post captures many of the pain points I see with Monaco in general: https://about.sourcegraph.com/blog/migrating-monaco-codemirror

![image](https://github.com/vizhub-core/vzcode/assets/68416/45386e01-40d6-488f-955c-e9f29c3b4c76)

Thanks for the question!

**Comment by curran** [comment]
This is the single most valuable feature of VSCode that I really miss when using VZCode.
We are already using the TypeScript language server, which may have this sort of functionality built in.
It's a larger piece though, not trivial.
Happy to work together on it if you want to dig in!
Needs some research on existing implementations with CodeMirror 6.
There's a chance someone has already figured this out in the open source world somewhere.

**Comment by curran** [comment]
This is the API:

https://github.com/typescript-language-server/typescript-language-server/tree/b224b878652438bcdd639137a6b1d1a6630129e4?tab=readme-ov-file#go-to-source-definition
