### ISSUE TITLE
File Creation UX Improvements

### ISSUE THREAD

**Issue by DomaDude123** [vizhub-core/vzcode#219]
In testing the closing of files and trying to tack down what happens when opening tabs, I've found it a little tedious to click the new file button each time I want to create a new file. 

What if we could create a new file with keyboard shortcut Alt+N?

**Comment by curran** [comment]
Yeah sure! That seems like it would add value re: usability.

I wonder if there's a similar shortcut in other editors, maybe VSCode... If so it would be neat to use the same keyboard shortcut, but Alt+N sounds great as a first version!

Thank you for this idea. Feel free to work on it if you feel so inspired!

**Comment by DomaDude123** [comment]
The new file shortcut in VSCode is CTRL-N. Unfortunately, this shortcut is already userd by most browsers to open a new tab. ALT-N seems like the closest alternative. Let me know if there is a different combination of keys that works better.

I implemented the new keyboard shortcut using ALT-N but ran into another minor quality of life change we could make. When the new-file shortcut is used in VSCode the new file is immediately ready to be typed into. In VZCode the user has to click the text editor before they start typing. This is a very minor change but I think it's part of what makes the new file shortcut so slick in VSCode.

I'm a little stuck on where to go next in adding this minor change. Could I maybe get some tips to point me in the right direction?

**Comment by curran** [comment]
>the user has to click the text editor before they start typing

The concept you're looking for is "focus". Try this: https://codemirror.net/docs/ref/#view.EditorView.focus

**Comment by curran** [comment]
Some ideas:

Similar to `useDynamicTheme`

```
const { editor } = editorCache.get(fileId)
```

**Comment by curran** [comment]
Is this WIP in a PR or branch? I don't see it.

Some notes from dogfooding VZCode:

Ideally after creating a new file, whether with a shortcut or with the new file button, the following should happen:

 * The file should be opened in a new tab
 * The editor should focus

**Comment by DomaDude123** [comment]
As of right now, when a user hits the shortcut the new file is created and it is set as the active editor. The only missing piece is focusing on the new editor window when it is created.

**Comment by curran** [comment]
Ah ok cool! So it sounds like this is what we have:

 * [X] After creating a new file with the keyboard shortcut, the file should open in a new tab
 * [ ] After creating a new file with the keyboard shortcut, the editor should focus
 * [ ] After creating a new file with the "new file" button, the file should open in a new tab
 * [ ] After creating a new file with the "new file" button, the editor should focus

Where is the new shortcut implemented? Did you push your branch or create a PR yet for it?
