### ISSUE TITLE
Delete Directory Confirmation Modal

### ISSUE THREAD

**Issue by DomaDude123** [vizhub-core/vzcode#224]
When a user deletes a directory it  prompts them with a confirmation as if they were deleting a file.

**Comment by curran** [comment]
Yup!

This is what it is now:

![image](https://github.com/vizhub-core/vzcode/assets/68416/d411679c-0947-4cda-8aad-82a30d5ae22a)

The functionality is correct, but the copy (text) needs to be updated to replace "File" with "Directory".

**Comment by curran** [comment]
I think @EvWhymark touched a lot of code related to this recently in https://github.com/vizhub-core/vzcode/pull/234

**Comment by curran** [comment]
Working on this
