### ISSUE TITLE
Gap Below Tabs

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#230]
![image](https://github.com/vizhub-core/vzcode/assets/68416/fffc4ba3-b183-42ef-bfc5-6be0c998dde7)

There is an unexpected gap below the tabs.

**Comment by curran** [comment]
Could be as simple as changing

```
    overflow-x: scroll;
```

to

```
    overflow-x: auto;
```

**Comment by DomaDude123** [comment]
Closed by Pull Request #231.
