### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by DomaDude123** [vizhub-core/vzcode#236]
Current scrollbar implementation is using a CSS default. The VSCode scrollbar is much thinner and has a sleeker look. Implementing a custom scrollbar would allow us to mimic VSCode's more closely.

Reference links:
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by curran** [comment]
This looks like it's done!



![Image](https://github.com/vizhub-core/vzcode/assets/68416/e983cc23-5a59-4107-b7df-3b7b7845b520)
