### ISSUE TITLE
Prettier Error Overlay Obscures Code

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#250]
Following a discussion in https://github.com/vizhub-core/vzcode/pull/249

User story:

As a user editing code that has a syntax error where the syntax error happens to fall beneath the error overlay, I want to be able to edit the code that is beneath the error overlay, so that I can resolve the syntax error.

Example screenshot:

![image](https://github.com/vizhub-core/vzcode/assets/68416/34995d21-4cec-45a8-857f-e5664cf23b47)

**Comment by Darmin-Geek** [comment]
The error could be inserted in-between lines, rather than as an overlay.

**Comment by nghongwatsang** [comment]
What do you mean by in-between lines? Would you want the error message to be displayed in the editor and result in pushing the code around it up or down?

**Comment by curran** [comment]
Some alternatives I see for how to solve:

 * Introduce a way to dismiss the prettier error overlay, for example an "X" in the upper right of it, to close it out so you can focus on the code below (note that there is no need to introduce UI to show it again after dismissing it, since it will pop up if the syntax error remains after editing)
 * Make the error overlay not an overlay at all, but rather give it dedicated space at the bottom, and shrink the code editor. That way the user could scroll the code into view if it was previously where the error message is

**Comment by curran** [comment]
There's also this alternative way of showing syntax errors, which may ultimately lead to phasing out the overlay concept entirely

https://github.com/vizhub-core/vzcode/issues/245

**Comment by curran** [comment]
One idea

![image](https://github.com/vizhub-core/vzcode/assets/68416/736a1ad3-67c1-42e2-9b90-ba5a2b141cae)

**Comment by curran** [comment]
Maybe we could re-use the "X" that we have already for closing tabs.

**Comment by nghongwatsang** [comment]
It's definitely a good option. But what would be the logic here in terms of how we implement it. Would x ing out mean that all future syntax errors are also hidden, or just for that specific one. And, in the case where it's just that specific one, how would we go about reshowing the error if the user accidentally clicked the x and still wants to see the error.

**Comment by curran** [comment]
I'm think the first version would just be hiding that specific error.

>how would we go about reshowing the error 

I think that takes care of itself, because as soon as the user types anything, Prettier will auto-run again, and if the syntax error is there it will show again.

**Comment by nghongwatsang** [comment]
Okay, that makes sense. Would you like me to work on implementing this today?

**Comment by nghongwatsang** [comment]
Also, the syntax error overlay doesn't disappear when you switch to a new file so we have to fix that.

**Comment by nghongwatsang** [comment]
The problem disappears when any file is edited, but I still believe we should find a way to remove the overlay because it can be a nuisance if someone is simply browsing through other files.

Ideas:
- Combine the two issues above and have the code "click" the x when a file is switched. 
- Create an additional way usePrettier runs in the specific situation when switching files. Rather than checking if the shareDB doc has been edited, instantly run usePrettier once at the start.

**Comment by curran** [comment]
>the syntax error overlay doesn't disappear when you switch to a new file so we have to fix that.

Great catch! I wonder if we might want to use a `Map` to track prettier errors per file, so we don't need to re-run Prettier every time you switch files. Ideally if you navigate to a different file, then back to a file with a Prettier error, that error would just show instantly, without having to re-run Prettier. Sort of similar to `editorCache`.

**Comment by curran** [comment]
I pulled in the UI for this in #277

![image](https://github.com/vizhub-core/vzcode/assets/68416/22262571-6aba-4938-8242-0bd93d2471d5)

What remains is to implement the correct logic for what happens when you click it.

```js
import { useCallback } from 'react';
import './style.scss';

// Feature flag for the button that dismisses the error.
const enableErrorDismiss = false;

export const CodeErrorOverlay = ({
  errorMessage,
}: {
  errorMessage: string | null;
}) => {
  const handleCloseClick = useCallback(() => {
    console.log('TODO dismiss the error');
  }, []);

  return errorMessage !== null ? (
    <pre className="vz-code-error-overlay">
      {errorMessage}
      {enableErrorDismiss ? (
        <div
          className={'bx bx-x error-dismiss-button'}
          onClick={handleCloseClick}
        ></div>
      ) : null}
    </pre>
  ) : null;
};
```

**Comment by nghongwatsang** [comment]
I'll start working on it

**Comment by curran** [comment]
Excellent! Many thanks.

**Comment by curran** [comment]
This is done.
