### ISSUE TITLE
Make color indicator bigger

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#268]
As a user editing code, I want to see the color indicator more clearly.

![image](https://github.com/vizhub-core/vzcode/assets/68416/737acc81-a8fb-4b91-b356-1380dfa1cb2f)

We could make it bigger.

This is defined in https://github.com/vizhub-core/vzcode/blob/main/src/client/CodeEditor/widgets.ts#L304

**Comment by Darmin-Geek** [comment]
I agree that the indicator should be bigger. However, I also think it should be bounded in size so that it does not increase the spacing between lines in a jarring way.
