### ISSUE TITLE
UX Improvements: Disallow Empty File Name

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#328]
As a user of VZCode creating a new file, I should not be able to click through "Create File" until I've entered a file name.

![image](https://github.com/vizhub-core/vzcode/assets/68416/e9401f4f-f521-4d49-a2f9-f2b9ab40ec20)

**Comment by curran** [comment]
This might help https://react-bootstrap.netlify.app/docs/components/buttons/#disabled-state

There's a field called `disabled` on the Button element we can use for this.

**Comment by DomaDude123** [comment]
@curran This worked perfectly! Do we want to put constraints on what users can name files? Should we disallow certain invalid file names? ( i.e. file names starting and ending with spaces, underscores, periods, or hyphens)

**Comment by DomaDude123** [comment]
@EvWhymark and I found a bug. Currently, a user can name a file with only spaces. The user is then unable to delete the file.  I'm working on a way to validate filenames, making use of the disabled field on the button element.

**Comment by curran** [comment]
Nice! Yeah let's only allow it if it's not all spaces. You can maybe use `string.trim() === ""` as the test.
