### ISSUE TITLE
TypeScript Linter: Update File with Each Request

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#336]
https://github.com/vizhub-core/vzcode/pull/335/files/e7cf729e914f3fc77216f0f906b268692d2dea7b#diff-e2b50b056500704b20f1ea54e0b788eaed9c52d4c207d093efce243e9cce694cR197

In `src/client/useTypeScript/worker.ts` line 197:

It's possible that a linting request is made before a completion request, and also before the debounced ShareDB updating logic has a chance to set the correct file content.

![image](https://github.com/vizhub-core/vzcode/assets/68416/38fe4d5c-daf3-401b-bff5-6929db517088)

In fact while testing I received this error, indicating that the TS FS did not have the latest. We may want to update it here as well, on each request, just like we do for the completions.

**Comment by EvWhymark** [comment]
When running the file updates alongside the linter request it really messes up our typescript environment. Our autocompletions still work however the linter does not properly update as we type text. My current thoughts are that we cant update file content as we are running our linter request. We need to do it some other way. Maybe as a independent request to the web worker?
