### ISSUE TITLE
Tab jumping to new field

### ISSUE THREAD

**Issue by DomaDude123** [vizhub-core/vzcode#338]
Currently, when a user hits tab the editor focus is brought onto another element of the webpage. This does not match the behavior of a tab in most code editors where a set number of spaces are added. Should tab have this new behavior? If so, how many spaces should tab insert?

**Comment by curran** [comment]
https://github.com/codemirror/dev/issues/238

https://codemirror.net/examples/tab/

**Comment by DomaDude123** [comment]
Code mirror specifically leaves the implicit behavior of tab on webpages for accessibility. This issue is not needed.
