### ISSUE TITLE
New icon for Rename (Edit)

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#463]
Following the work done in https://github.com/vizhub-core/vzcode/pull/462/files , this issue is about swapping out the existing edit icon with the new one, and also implementing the style changes (color, button style).

Old:
![image](https://github.com/vizhub-core/vzcode/assets/68416/60883dc5-60b4-45d4-9a4e-b35352e61c3c)

New:
![image](https://github.com/vizhub-core/vzcode/assets/68416/f3284086-20d2-4eb0-9157-c1dffd27542b)

The first version does not need to have a hover state, but if it's low hanging fruit, consider a hover state style like this (clickable area slightly brighter than the background):

![Image](https://github.com/vizhub-core/vzcode/assets/68416/173824ce-d21f-4924-95d5-1632b05c7e2d)

**Comment by chinm4** [comment]
Pull request to add Rename button thats resized and with hovering! :)
