### ISSUE TITLE
Feedback:Feedback button

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#512]
For a more intuitive user experience on Vizhub, incorporating a dedicated 'Feedback' button prominently at the top of the visualization interface is advisable. This change would clearly distinguish between reporting technical issues and providing general feedback, addressing the current confusion where users might mistakenly use the 'Bug Report' button for feedback purposes. By making this adjustment, Vizhub would offer a straightforward way for users to share their insights or suggestions, enhancing user engagement and facilitating continuous improvement of the platform.

**Comment by curran** [comment]
Great ideas!

We currently have two feedback buttons:

"Report Bug" in VZCode

![image](https://github.com/vizhub-core/vzcode/assets/68416/d3c7c680-b2f3-4a06-b828-9ec5a3a46312)

Also for VizHub feedback there is a "Feedback" button on the home page:

![image](https://github.com/vizhub-core/vzcode/assets/68416/448f12a8-d561-4fb7-a984-cf9a8be93e3c)

Both of these point to a GitHub issue creation page. I think this adequately solves the issue.
