### ISSUE TITLE
Configurable Font

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#514]
Enhancing the editor with a feature that allows users to customize the font provides a personalized and comfortable coding experience. This improvement would cater to individual preferences and accessibility needs, enabling users to select the font style and size best suits their visual requirements for optimal readability and productivity.

**Comment by curran** [comment]
This would be a great addition to the Settings Modal, which already has an option for theme!

I could imagine adding another option there to select various fonts.

![image](https://github.com/vizhub-core/vzcode/assets/68416/95d4dbac-8cd2-4178-95de-9ac2159d0662)

**Comment by curran** [comment]
Sounds good! We probably should start with a curated list of monospace fonts that are popular. That would allow phased development where a very simple solution comes first (standard dropdown), then after that we can consider a searchable dropdown.

Here's a good set of fonts to start with:

Roboto Mono (currently in use)

![image](https://github.com/vizhub-core/vzcode/assets/68416/067df067-c71b-4801-889a-8e3de58374ee)

Inconsolata

![image](https://github.com/vizhub-core/vzcode/assets/68416/0d982b16-d562-4c51-bbd3-23c983e67c8a)

Source Code Pro

![image](https://github.com/vizhub-core/vzcode/assets/68416/7f064944-47de-42a4-bb79-b65e7bd89fc6)

Ubuntu Mono

![image](https://github.com/vizhub-core/vzcode/assets/68416/651d65d8-b7c2-4fad-ab61-70371db11092)

JetBrains Mono

![image](https://github.com/vizhub-core/vzcode/assets/68416/e9881dc5-5604-457c-abc1-9222e9ee662d)

Fira Code

![image](https://github.com/vizhub-core/vzcode/assets/68416/de5c0265-87d8-42c5-858d-6fdbea819eed)

**Comment by curran** [comment]
@nitanagdeote The font is now configurable! Ubuntu Mono and 18px are available.
