### ISSUE TITLE
Autocomplete in HTML

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#517]
![image](https://github.com/vizhub-core/vzcode/assets/13540669/1194565f-e3f5-4be5-980c-9d2c0991bcdc)
Autocomplete does not suggest the declared variable in index.html inside the script tag.
[](https://vizhub.com/nitanagdeote/2cbbf6f81d784c1089d618d6eb8896f5?file=index.html)

**Comment by curran** [comment]
Ah yes, it only works in JavaScript files at the moment. It would be nice if it worked in HTML files too! And CSS for that matter.

**Comment by curran** [comment]
Oh hey! This should be possible as the CodeMirror HTML language package has completion support
 

https://github.com/codemirror/lang-html/

**Comment by michaelhelper** [comment]
Code mirror autocomplete documentation: https://codemirror.net/examples/autocompletion/

**Comment by curran** [comment]
Summary of scope:

 * Ideally we replicate what is working already for JS, which is that suggestions automatically populate (without hitting CTRL+Space)

![Image](https://github.com/vizhub-core/vzcode/assets/68416/0facd3a0-0db7-4c47-bae0-394228fe478d)

 * The auto-closing of tags would also be nice to pull in, if it's easy , but no big deal if not

**Comment by curran** [comment]
Closed in https://github.com/vizhub-core/vzcode/pull/779 woohoo!
