### ISSUE TITLE
Scrolling with mouse goes left to right

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#524]
https://vizhub.com/nitanagdeote/ee7482e2ddfe42668cec713c5a32eb92?file=README.md

I'm not sure this is just the mouse problem. Thanks.

**Comment by curran** [comment]
Cannot reproduce. Can you share what exactly you did to make it happen? Or ideally a screen grab video? Thanks!

**Comment by nitanagdeote** [comment]
I will show you a demo.

**Comment by curran** [comment]
Sharing a screen recording would be a great way to show the demo.

I like this software called Peek for recording quick screen grabs https://github.com/phw/peek

It's available for Ubuntu

**Comment by curran** [comment]
Oh is this what you mean?

https://github.com/vizhub-core/vzcode/assets/68416/6a33c4d1-342f-4ef0-823d-f90f8db8f63b

**Comment by curran** [comment]
This is a valid issue. I would frame the task here as:

 * [ ] Make the CodeMirror editor take up 100% of the available width while always showing a vertical scrollbar on the right

**Comment by darrenW04** [comment]
> This is a valid issue. I would frame the task here as:
> 
> * [ ]  Make the CodeMirror editor take up 100% of the available width while always showing a vertical scrollbar on the right

If the CodeMirror takes up 100%, what happens when there is a super long one liner. Won't that just make it super zoomed out.

**Comment by curran** [comment]
![image](https://github.com/vizhub-core/vzcode/assets/68416/290a3027-90ba-4f84-a3e4-320004362e61)

Try `width: 100%` applied to `cm-editor`.
