### ISSUE TITLE
Stroke may not require on these color picking circles

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#590]
![image](https://github.com/vizhub-core/vzcode/assets/13540669/e3c35033-bb42-4a03-9467-ff061cc04dfa)

**Comment by curran** [comment]
I agree! I changed the style so now it looks like this:

![image](https://github.com/vizhub-core/vzcode/assets/68416/7009cf5c-c5b9-49e8-8609-bbdb67ce8bb5)
