### ISSUE TITLE
Drag here border 

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#592]
![image](https://github.com/vizhub-core/vzcode/assets/13540669/f3dd0cdf-94ae-47e3-906c-e2fedbd5af05)

- [ ] The border is too thick.
- [ ] There should be a gap between the file and the 'drag here' box.
- [ ] drag box can even go at the bottom of all files

**Comment by curran** [comment]
Closed in https://github.com/vizhub-core/vzcode/pull/587

We plan to make the entire sidebar a drag target.
