### ISSUE TITLE
Active file does not persist across refreshes

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#636]
https://vizhub.com/nitanagdeote/4f64bfb0bf9449068e6cf5f759c2bfdd?edit=files&file=index.js&tabs=index.js%7Eviz.js

To reproduce:

 * Open two files
 * Switch between them
 * Refresh the page
 * Observe that the file open after the refresh is _not_ the same file as was open before the refresh

**Comment by curran** [comment]
This could be an issue with the way React Router is used.

Potentially related to #495
