### ISSUE TITLE
Bug: You can create files with duplicate names, which then deletes the originanal file.

### ISSUE THREAD

**Issue by enuessle** [vizhub-core/vzcode#653]
In the VZCode interface, naming file to a name that already exists works, and creates a new file in VZCode.
![Two Index js](https://github.com/vizhub-core/vzcode/assets/77037513/9d6c26c3-22bd-4094-90b1-11d8ec94e484)

On the file system however it just ends up deleting all the contents of the original file, which goes against what the VZCode interface is saying
![Deletes Contents](https://github.com/vizhub-core/vzcode/assets/77037513/5024c190-2145-4c2c-920a-d80111a3a57b)

Ideally it should work like VSCode and not let you name something if it already exists, or just add some numeral at the end to mark it as separate and not break things.

**Comment by curran** [comment]
Aha! Very nice observation. I'd definitely welcome this change. Thanks for spotting this!
