### ISSUE TITLE
Presence: Usernames

### ISSUE THREAD

**Issue by Anooj-Pai** [vizhub-core/vzcode#68]

**Comment by curran** [comment]
Agree this would be nice to have.

Here's an example that does it, maybe we can draw some ideas from here https://github.com/share/sharedb/tree/master/examples/rich-text-presence

**Comment by curran** [comment]
![image](https://github.com/vizhub-core/vzcode/assets/68416/67451b02-807b-4113-8478-87a08b7d54fe)

VSCode liveshare UI example

**Comment by curran** [comment]
https://github.com/yjs/y-codemirror/blob/main/src/y-codemirror.js#L180C2-L180C36

**Comment by curran** [comment]
To clarify scope of this issue - this is about displaying usernames near the presence cursors.

![image](https://github.com/vizhub-core/vzcode/assets/68416/420b310f-961a-4975-92d4-cbeca7918791)

We can probably do something similar to this implementation, which does the exact thing we want:

https://github.com/yjs/y-codemirror/blob/main/src/y-codemirror.js#L180C2-L180C36
