### ISSUE TITLE
Add a switch to toggle auto-follow on and off

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#739]
![image](https://github.com/vizhub-core/vzcode/assets/68416/682894cb-a1cc-4947-8745-f92a1ff9326f)

As a VZCode user who is currently auto-following the other remote users, I want to be able to turn off auto-follow for me, so that I can work on code changes without being interrupted by the auto-follow feature.

 * [X] Add a pin icon SVG component (`src/client/Icons/PinSVG.tsx`)
 * [x] Add the pin icon to the UI in the upper right of the editor window
 * [x] Clicking on that should toggle the auto-follow on and off

**Comment by curran** [comment]
Alternatively, this could go into the existing settings, which might be easier as a first step than the SVG icon.

**Comment by curran** [comment]
[Push pin icons](https://www.google.com/search?q=push+pin+icon+svg&udm=2&client=ubuntu-chr&sa=X&ved=2ahUKEwijqZ2gteCGAxXQF1kFHVTCAFwQrNwCegQIbhAA&biw=1920&bih=929&dpr=1)

![image](https://github.com/vizhub-core/vzcode/assets/68416/a25b7d87-fa17-4354-b841-53a49ec1e1a0)

Starting point for icon search

**Comment by curran** [comment]
This might be a good one

https://primer.style/foundations/icons/pin-24

![image](https://github.com/vizhub-core/vzcode/assets/68416/79d2e57b-4184-4f4f-9b88-0feaaf3ce36b)

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="m16.114 1.553 6.333 6.333a1.75 1.75 0 0 1-.603 2.869l-1.63.633a5.67 5.67 0 0 0-3.395 3.725l-1.131 3.959a1.75 1.75 0 0 1-2.92.757L9 16.061l-5.595 5.594a.749.749 0 1 1-1.06-1.06L7.939 15l-3.768-3.768a1.75 1.75 0 0 1 .757-2.92l3.959-1.131a5.666 5.666 0 0 0 3.725-3.395l.633-1.63a1.75 1.75 0 0 1 2.869-.603ZM5.232 10.171l8.597 8.597a.25.25 0 0 0 .417-.108l1.131-3.959A7.17 7.17 0 0 1 19.67 9.99l1.63-.634a.25.25 0 0 0 .086-.409l-6.333-6.333a.25.25 0 0 0-.409.086l-.634 1.63a7.17 7.17 0 0 1-4.711 4.293L5.34 9.754a.25.25 0 0 0-.108.417Z"></path></svg>
```

**Comment by curran** [comment]
Added that icon in the file `src/client/Icons/PinSVG.tsx`!

In this PR https://github.com/vizhub-core/vzcode/pull/749

**Comment by curran** [comment]
The best approach probably is to add a field to `VZState` like `isFollowEnabled`, then wire it through, similar to how the settings modal works. Good luck @DaCatDude !

**Comment by DaCatDude** [comment]
I actually did not add it to the corner of the edior, but rather to the pre-existing icons on the side bar (I honestly thought it would be more appropriate being over there). If this isnt how you envisioned it looking, ill be more than happy to relocate it.
