### ISSUE TITLE
Set up Dependabot

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#742]
If it's free for open source, let's set this up as it would save time.

**Comment by michaelhelper** [comment]
https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide

looks like only the owner of the repo can set up Dependabot.

**Comment by michaelhelper** [comment]
![Image](https://github.com/vizhub-core/vzcode/assets/100871194/a33023a7-c92e-4cb1-9360-10147e1201c5)
