### ISSUE TITLE
Icons For Keyboard Shortcuts

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#799]
example of the icons in vs code:
![image](https://github.com/user-attachments/assets/41f166f7-e446-4225-8baf-ea47e83f2652)

**Comment by IBurntMyBagel** [comment]
Progress this week:
Before: ![image](https://github.com/user-attachments/assets/fb7b5b37-0cbf-4c21-9890-20458e73ce56)

After: ![image](https://github.com/user-attachments/assets/a9d2ad75-49cf-4c50-9132-81fd397516c0)

Experimenting and learning more about typescript. Looked into the popups when hovering over the run button, rename file, and delete file. Should the next step be a shortcut popup for dragging number feature and when the user hovers over the hex color?

Example: 
![image](https://github.com/user-attachments/assets/ac7eb7ca-da3b-4529-9884-f4cda8955bf3)

**Comment by IBurntMyBagel** [comment]
Update: Added the little shortcut pop-up whenever a user's mouse hovers over the color circle
Branch Commit: https://github.com/vizhub-core/vzcode/commit/be80873841734984f139ae42ddac91c5871f8711
Video:

https://github.com/user-attachments/assets/d22b88e3-d06f-426f-a6d3-afb0b1940792

**Comment by curran** [comment]
Oh wow that's amazing! Excellent work!
