### ISSUE TITLE
Add folders to the file system

### ISSUE THREAD

**Issue by Anooj-Pai** [vizhub-core/vzcode#80]

**Comment by curran** [comment]
This would involve 

 * Reading directories (the top-level listing) from the file system
 * Modifying the sidebar to show directories differently from files, perhaps with an arrow indicating they can be "opened"
 * When "opening" a directory, the listing of files within that directory should be read from the file system (just like we do now, but for within that directory)
 * That listing should be translated into our ShareDB data structure. Proposed structure: make `name` contain forward slashes to indicate where it falls in the directory tree. For example `foo/bar.js` would mean it's `bar.js` within the `foo` directory.
 * The sidebar list needs to be made to represent the known directory tree using a visual hierarchy
 * Interactions to "open" and "close" directories in the sidebar should be implemented
 * Ideally the entire sidebar should be navigable using accessibility best practices like keyboard navigation

This is a neat example https://files.paciellogroup.com/training/WWW2012/samples/Samples/aria/tree/index.html

**Comment by curran** [comment]
Some design inspiration from GitHub CI

![image](https://user-images.githubusercontent.com/68416/228497974-b4e03139-a9bb-4699-afca-022bc5b7a12b.png)

https://github.com/share/sharedb/actions/runs/4552627958/jobs/8028200864

**Comment by curran** [comment]
For the sidebar UI, this might be a great example to draw from:

https://github.com/adobe/react-spectrum/blob/6829b861ad4acfa8c0145f4fd652803f353f47db/packages/%40react-spectrum/listbox/stories/ListBox.stories.tsx#L715

This uses [react-aria](https://react-spectrum.adobe.com/react-aria/index.html) which is a reputed library that implements accessibility and keyboard navigation. Apparently they have this example that uses tree data! This is amazing.

I think we need to map the file system to the tree data structure expected by this library, and it should in theory "just work".

**Comment by curran** [comment]
I think the easiest way to do this would be to recursively load all files and folders up front, and represent the files by setting the name to be their paths. That way we can leverage all the existing ShareDB infrastructure without any modifications. The sidebar would need to be "intelligent" enough to parse out the tree from the names.

Here's some existing code that does this: https://github.com/vizhub-core/vizhub/blob/main/vizhub-v2/packages/neoFrontend/src/pages/VizPage/Body/Editor/FilesSection/FileTree/getFileTree.js

```js
import { packageJSON } from '../../../../../../featureFlags';

export const getFileTree = (files) => {
  const tree = { name: 'files' };
  files.forEach((file) => {
    const path = file.name.split('/');
    const n = path.length;
    let node = tree;

    // Walk the path.
    for (let i = 0; i < n - 1; i++) {
      // Search for an existing child.
      let child;
      const name = path[i];
      if (node.children) {
        for (let j = 0; j < node.children.length; j++) {
          const nodeChild = node.children[j];
          if (nodeChild.name === name) {
            child = nodeChild;
            break;
          }
        }
      }

      // Create a child if none with matching name exists.
      if (!child) {
        child = {
          name: path[i],
          path: path.slice(0, i + 1).join('/'),
        };
        (node.children || (node.children = [])).push(child);
      }

      node = child;
    }

    (node.children || (node.children = [])).push({
      name: path[n - 1],
      file,
    });
  });
  return tree;
};
```

There are also tests for this! We can port those tests also into this repo: https://github.com/vizhub-core/vizhub/blob/main/vizhub-v2/packages/neoFrontend/src/pages/VizPage/Body/Editor/FilesSection/FileTree/getFileTree.test.js

**Comment by curran** [comment]
Interesting resources:

 * https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role
 * https://spectrum.adobe.com/page/tree-view/

**Comment by curran** [comment]
One thing to consider is: do we need to support empty directories?

What if a user wants to use VZCode to create a directory, then after that put a file into it? That should be possible. The intermediate state of having an empty directory is required in this case.

So the question is, how to we represent an empty directory?

I propose we represent it as a "file" whose "name" field has a trailing slash.

Note that if there are files inside a directory, then we don't need any explicit representation of the directory, because it's represented implicitly in the paths of the various files.

We just need to be careful to always create the empty directory "file" when it is needed, for example if we delete all the files in a directory.
