### ISSUE TITLE
Block Cursor

### ISSUE THREAD

**Issue by jeffrey-asm** [vizhub-core/vzcode#826]
A block cursor as a potential VZCode editor configuration option would be perfect, which would look similar to the following:

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/a8945761-82de-44d3-a57c-c49ec8d305f5">

**Comment by curran** [comment]
Not convinced. I don't think that's the default in VSCode.

This is what my cursor looks like in VSCode, default style I think.

![Image](https://github.com/user-attachments/assets/5d5906a5-62f9-4b92-92c6-5f874d5b4db6)
