### ISSUE TITLE
Suppress useless TypeScript warning about type unknown

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#842]
![image](https://github.com/user-attachments/assets/34ca0b15-8154-484b-9c95-a0209b792d1f)

Repro:

```js
  const filters = Object.entries(brushedIntervals);
  const filteredData = data.filter((d) => {
    for (const [column, interval] of filters) {
      const [min, max] = interval;
      if (d[column] < min || d[column] > max) {
        return false;
      }
    }
    return true;
  });
```

**Comment by curran** [comment]
See this file 

```
src/client/useTypeScript/worker/constants.ts
```

and this PR as a reference:

https://github.com/vizhub-core/vzcode/pull/711/files

**Comment by TroyG-11** [comment]
When reproducing the code for the error, it seemed to work as intended. Checking further into the code the handler also seems to handle Unknown types already.

**Comment by curran** [comment]
Oh interesting! Thanks for investigating.

![image](https://github.com/user-attachments/assets/c6b5e343-8028-4e47-bd7f-fd9e94c16618)

When I try it, I still get that lint warning, on the latest `main`. Are you able to reproduce this?

The goal is to make it not show that error.

If you set `const debug = true;` on line 11 of `src/client/useTypeScript/worker/index.ts`, you can inspect the error code.

![image](https://github.com/user-attachments/assets/1c8c4d41-d6e4-440c-a4dd-af5c91d35cd8)

Further inspection reveals an error code of `2488` for that one.

![image](https://github.com/user-attachments/assets/b191e478-0acd-4a33-b6e9-86a77ba5574a)

@TroyG-11 Please add `2488` to the list of excluded error codes in `src/client/useTypeScript/worker/constants.ts` to close this issue. Thanks!

**Comment by TroyG-11** [comment]
https://github.com/vizhub-core/vzcode/pull/861

**Comment by curran** [comment]
Closed in https://github.com/vizhub-core/vzcode/pull/861
